---
title: "Form and Content in 17th-Century Haarlem Still Lifes"
author: "Matthew Lincoln"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Form and Content in 17th-Century Haarlem Still Lifes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r libraries, include = FALSE}
library(dutchtabletopsdata)
library(purrr)
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(ggrepel)
library(forcats)
library(randomForest)
library(broom)
knitr::opts_chunk$set(fig.width = 9, fig.height = 9, warning = FALSE, echo = FALSE, cache = TRUE, dev = "pdf")
```

```{r create_model}
# Model artists with only n or more paintings
n_ptg <- 5
dt_reveleved <- dt_compiled %>% 
  mutate(
    artist_relationship = recode_factor(artist_relationship, "Co-painter" = "After", "Possible" = "After"),
    artist_union = as.factor(paste(artist, artist_relationship, sep = " - ")))

cleared_artists <- unique(filter(group_by(dt_reveleved, artist), n() >= n_ptg)$artist)
cleared_artist_union <- unique(filter(group_by(dt_reveleved, artist_union), n() >= n_ptg)$artist_union)

dt_valid <- dt_reveleved %>% 
  filter(artist %in% cleared_artists, artist_union %in% cleared_artist_union) %>% 
  select(one_of(comp_vars(), motif_vars(), "year_early", "year_late", "artist", "artist_union", "artist_relationship")) %>%
  mutate(year = (year_early + year_late) / 2, artist_union = fct_drop(artist_union)) %>% 
  dmap_if(function(x) is.character(x) | is.logical(x), as.factor)

partition <- function(df, response_var, ratio = 0.2) {
  n_obs <- nrow(df)
  all_resp <- df[[response_var]]
  all_data <- df %>% 
    select(one_of(comp_vars(), motif_vars())) %>% 
    na.roughfix()
  test_index <- sample(seq_len(n_obs), size = ratio * n_obs, replace = FALSE)
  test_data <- all_data[test_index,]
  test_resp <- all_resp[test_index]
  train_data <- all_data[-test_index,]
  train_resp <- all_resp[-test_index]
  
  def_index <- df[["artist_relationship"]] == "Definite"
  def_data <- all_data[def_index,]
  def_res <- all_resp[def_index]
  unk_data <- all_data[-def_index,]
  unk_res <- all_resp[-def_index]
  
  l <- list(
    allx = all_data,
    ally = all_resp,
    defx = def_data,
    defy = def_res,
    unkx = unk_data,
    unky = unk_res,
    x = train_data,
    y = train_resp,
    xtest = test_data,
    ytest = test_resp)
  
  if (is.numeric(train_resp)) {
    quant_breaks <- quantile(train_resp, probs = seq(0, 1, length.out = 5))
    quant_labels <- quant_breaks[1:4]
    
    l$yquant = cut(train_resp, breaks = quant_breaks, labels = quant_labels)
    l$minsamp = round(n_obs/5) - 1
  } else {
    l$yquant = train_resp
    l$minsamp = last(fct_count(train_resp, sort = TRUE)[["n"]])
  }
  
  l
}

artist_data <- partition(dt_valid, "artist")
year_data <- partition(dt_valid, "year")
artist_union_data <- partition(dt_valid, "artist")
```

```{r run_models}
# artist_motif_forest <- randomForest(x = select(artist_data$allx, one_of(motif_vars())), y = artist_data$ally, ntree = 500, importance = TRUE, proximity = TRUE, keep.forest = TRUE)
# artist_comp_forest <- randomForest(x = select(artist_data$allx, one_of(comp_vars())), y = artist_data$ally, ntree = 500, importance = TRUE, proximity = TRUE, keep.forest = TRUE)
# artist_all_forest <- randomForest(x = artist_data$allx, y = artist_data$ally, ntree = 500, importance = TRUE, proximity = TRUE, keep.forest = TRUE)
# 
# 
# 
# artist_union_motif_forest <- randomForest(x = select(artist_union_data$allx, one_of(motif_vars())), y = artist_union_data$ally, ntree = 500, importance = TRUE, proximity = TRUE, keep.forest = TRUE)
# artist_union_comp_forest <- randomForest(x = select(artist_union_data$allx, one_of(comp_vars())), y = artist_union_data$ally, ntree = 500, importance = TRUE, proximity = TRUE, keep.forest = TRUE)
# artist_union_all_forest <- randomForest(x = artist_union_data$allx, y = artist_union_data$ally, ntree = 500, importance = TRUE, proximity = TRUE, keep.forest = TRUE)

artist_motif_forest <- randomForest(
  x = select(artist_union_data$defx, one_of(motif_vars())), 
  y = artist_union_data$defy, 
  xtest = select(artist_union_data$unkx, one_of(motif_vars())),
  ytest = artist_union_data$unky,
  importance = TRUE,
  proximity = TRUE,
  keep.forest = TRUE)

artist_comp_forest <- randomForest(
  x = select(artist_union_data$defx, one_of(comp_vars())), 
  y = artist_union_data$defy, 
  xtest = select(artist_union_data$unkx, one_of(comp_vars())),
  ytest = artist_union_data$unky,
  importance = TRUE,
  proximity = TRUE,
  keep.forest = TRUE)
```

```{r show_error}
error <- function(rf, test = FALSE) {
  if (test) {
    er <- rf[["test"]][["err.rate"]]
  } else {
    er <- rf[["err.rate"]]
  }
  
  er %>% 
    as.data.frame() %>%
    slice(nrow(.)) %>% 
    gather(actual, error_rate, seq_len(ncol(.))) %>% 
    filter(!(actual %in% c("OOB", "Test")))
}
  
dual_error_data <- bind_rows(
  definite = bind_rows(
    motif = error(artist_motif_forest),
    composition = error(artist_comp_forest),
    .id = "predictor_type"),
  unknown = bind_rows(
    motif = error(artist_motif_forest, test = TRUE),
    composition = error(artist_comp_forest, test = TRUE),
    .id = "predictor_type"),
  .id = "is_definite") %>% 
  spread(predictor_type, value = error_rate) %>% 
  unite("vals", composition, motif) %>% 
  spread(is_definite, value = vals) %>% 
  separate(definite, into = c("definite_motif", "definite_composition"), sep = "_", convert = TRUE) %>% 
  separate(unknown, into = c("unknown_motif", "unknown_composition"), sep = "_", convert = TRUE)

dual_error_plot <- function(df, pop = NULL) {
  
  if (is.null(pop)) {
    p <- ggplot(df, aes(x = definite_composition, y = definite_motif, color = actual))
  } else {
    p <- ggplot(df, aes(x = definite_composition, y = definite_motif, color = actual, alpha = actual == pop)) +
      scale_alpha_discrete(guide = FALSE)
  }
  
  p +
    geom_hline(yintercept = 0.5, linetype = 2) + 
    geom_vline(xintercept = 0.5, linetype = 2) +
    geom_segment(aes(xend = unknown_composition, yend = unknown_motif), size = 1, arrow = arrow()) +
    geom_label_repel(aes(label = actual)) +
    scale_color_brewer(palette = "Dark2", guide = FALSE) +
    theme_bw() +
    xlim(0, 1) +
    ylim(0, 1)
}

dual_error_plot(dual_error_data, pop = "Gerrit Heda")
```

```{r tween_plot}
dual_error_data <- bind_rows(
  definite = bind_rows(
    motif = error(artist_motif_forest),
    composition = error(artist_comp_forest),
    .id = "predictor_type"),
  unknown = bind_rows(
    motif = error(artist_motif_forest, test = TRUE),
    composition = error(artist_comp_forest, test = TRUE),
    .id = "predictor_type"),
  .id = "is_definite") %>% 
  spread(predictor_type, error_rate)

kdata <- dual_error_data %>% 
  mutate_if(is.character, funs(as.factor)) %>% 
  split(f = dual_error_data$is_definite)

library(tweenr)
ts <- tween_states(kdata, tweenlength = 10, statelength = 5, ease = "quadratic-in", nframes = 300)
library(gganimate)

p <- ggplot(ts, aes(x = composition, y = motif, color = actual, frame = .frame)) +
  geom_hline(yintercept = 0.5, linetype = 2) + 
    geom_vline(xintercept = 0.5, linetype = 2) +
    geom_point(size = 3) +
    geom_label_repel(aes(label = actual)) +
    scale_color_brewer(palette = "Dark2", guide = FALSE) +
    theme_bw() +
    xlim(0, 1) +
    ylim(0, 1)
gg_animate(p, interval = 1/32)
```

```{r qualified}
bind_rows(
  motif = error(artist_union_motif_forest),
  composition = error(artist_union_comp_forest),
  .id = "predictor_type") %>% 
  filter(actual != "OOB") %>% 
  separate(actual, into = c("artist", "qualification"), sep = "-", remove = FALSE) %>%
  spread(predictor_type, value = error_rate) %>% 
  ggplot(aes(x = composition, y = motif, color = artist)) +
  geom_hline(yintercept = 0.5, linetype = 2) + 
  geom_vline(xintercept = 0.5, linetype = 2) +
  geom_point(aes(shape = qualification), size = 4) +
  geom_label_repel(aes(label = actual)) +
  theme_bw() +
  xlim(0, 1) +
  ylim(0, 1)

```

```{r confusion}
confusion <- function(rf) {
  rf[["confusion"]] %>% 
    as.data.frame() %>% 
    rownames_to_column(var = "actual") %>% 
    gather(predicted, times, 2:ncol(.)) %>% 
    filter(predicted != "class.error")
}

write_clip(data.frame(actual = artist_data$ally, motif_predicted = artist_motif_forest$predicted, composiiton_predicted = artist_comp_forest$predicted))
```

```{r}

write_clip()

data_frame(real = year_data$ally, predicted = year_forest$predicted) %>% 
  ggplot(aes(x = real, y = predicted)) +
  geom_linerange(aes(x = real, ymin = predicted, ymax = real, color = predicted > real)) +
  geom_point() +
  xlim(1600, 1700) +
  ylim(1600, 1700) +
  geom_abline(slope = 1, intercept = 0, color = "gray") +
  theme_bw() +
  scale_color_discrete(guide = FALSE) +
  geom_smooth(method = "lm")
```

```{r feature_power}
df <- all_data
var_name <- "LV"
simulate_data <- function(df, var_name) {
  
}
```



